### PR TITLE
avoids fatal error for services with unknown service descriptions

### LINKED ISSUE #719: Waiter should recover gracefully from missing service description
The current behavior of Waiter when it can't find a corresponding Service Description for a given Service ID is to throw a fatal error and crash (sample stack trace included below). This opens the possibility for a DoS against Waiter by a user injecting a maliciously-formed object into Marathon or Kubernetes.

On a semi-related note, it would be better if fatal errors were logged as `CRITICAL` rather than `ERROR` to help us distinguish them from recoverable errors.

```
2019-04-28 23:32:48,905 ERROR waiter.state [async-dispatch-40] - [CID=router-state-maintainer] Fatal error in router-state-maintainer!
clojure.lang.ExceptionInfo: No description found! {:service-id "waiter-service-kitchen-b3a1e47ef340421a08d46f03e4cdf6c2"}
        at waiter.service_description$eval27429$fetch_core__27439.doInvoke(service_description.clj:756)
        at clojure.lang.RestFn.invoke(RestFn.java:521)
        at waiter.service_description$refresh_service_descriptions.invokeStatic(service_description.clj:764)
        at waiter.service_description$refresh_service_descriptions.invoke(service_description.clj:758)
        at waiter.core$fn__44416$fnk44414_positional__44417$refresh_service_descriptions_fn__44418.invoke(core.clj:835)
        at waiter.state$start_router_state_maintainer$fn__40652$state_machine__10453__auto____40685$fn__40688.invoke(state.clj:1223)
        at waiter.state$start_router_state_maintainer$fn__40652$state_machine__10453__auto____40685.invoke(state.clj:1223)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async$ioc_alts_BANG_$fn__10682.invoke(async.clj:384)
        at clojure.core.async$do_alts$fn__10614$fn__10617.invoke(async.clj:253)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__5415$fn__5416.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by shamsimam**
## Changes proposed in this PR

- avoids fatal error for services with unknown service descriptions

## Why are we making these changes?

We should be resilient to invalid services showing up in scheduler queries.

Resolves #719.

### CODE REVIEW

File: waiter/src/waiter/service_description.clj [hunk 1]
```diff
@@ -765,12 +765,19 @@
...
+   Returns the set of service-ids which have valid service descriptions."
   [kv-store service-ids]
-  (doseq [service-id service-ids]
-    (when-not (fetch-core kv-store service-id :refresh false)
-      (log/info "refreshing the service description for" service-id)
-      (fetch-core kv-store service-id :nil-on-missing? false :refresh true))))
+  (->> service-ids
+       (filter
+         (fn [service-id]
+           (if (or (fetch-core kv-store service-id :refresh false)
```
Comment (DaoWen) [inline waiter/src/waiter/service_description.clj]: I think this might be easier to read:
```
(or (fetch-core kv-store service-id :refresh false)
    (log/info "refreshing the service description for" service-id)
    (fetch-core kv-store service-id :refresh true)
    (log/warn "filtering" service-id "as no matching service description was found"))
```

File: waiter/test/waiter/service_description_test.clj [hunk 2]
```diff
@@ -1651,7 +1651,11 @@
     (is (nil? (kv/fetch cache-kv-store (service-id->key service-id-3))))
     (is (= (service-id->service-description service-id-4) (kv/fetch cache-kv-store (service-id->key service-id-4))))
 
-    (refresh-service-descriptions cache-kv-store #{service-id-1 service-id-2 service-id-3 service-id-4})
+    (let [service-ids #{service-id-1 service-id-2 service-id-3 service-id-4}]
```
Comment (DaoWen) [inline waiter/test/waiter/service_description_test.clj]: I _really_ dislike threading into macros like `(is)`. I think this is much easier to read:
```
    (let [service-ids #{service-id-1 service-id-2 service-id-3 service-id-4}
          service-ids-in (conj service-ids "service-id-unknown1" "service-id-unknown2")
          service-ids-out (refresh-service-descriptions cache-kv-store service-ids-in)]
      (is (= service-ids service-ids-out)))
```

File: waiter/src/waiter/service_description.clj (hunk 1 above)
Comment (shamsimam) [reply waiter/src/waiter/service_description.clj]: Done.

File: waiter/test/waiter/service_description_test.clj (hunk 2 above)
Comment (shamsimam) [reply waiter/test/waiter/service_description_test.clj]: Done.
