### PR TITLE
Invalid token header should report 400 instead of 500

### LINKED ISSUE #454: Invalid token header should report 400 instead of 500
We should validate the token using the `waiter.token/valid-token-re` regex and use a memoized function to minimize the overhead of this validation. Failing the validation should report a `400` Client error.

```
$ curl -i -H"x-waiter-token: invalid/token" http://localhost:9091/hello
HTTP/1.1 500 Server Error
Content-Type: text/plain
x-cid: e322bca34794-11337f17bb43b7fa
Transfer-Encoding: chunked
```

The internal error logs point to it being detected at the `kv-store` layer.
```
2018-09-12 15:16:13,663 ERROR waiter.util.utils [qtp413715958-77] - [CID=e322bca34794-11337f17bb43b7fa] #error {
 :cause Key may not contain '/'
 :data {:key invalid/token}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Internal error
   :data {:status 500}
   :at [clojure.core$ex_info invokeStatic core.clj 4617]}
  {:type clojure.lang.ExceptionInfo
   :message Key may not contain '/'
   :data {:key invalid/token}
   :at [clojure.core$ex_info invokeStatic core.clj 4617]}]
 :trace
 [[clojure.core$ex_info invokeStatic core.clj 4617]
  [clojure.core$ex_info invoke core.clj 4617]
  [waiter.kv$validate_zk_key invokeStatic kv.clj 97]
  [waiter.kv$validate_zk_key invoke kv.clj 92]
  [waiter.kv.ZooKeeperKeyValueStore retrieve kv.clj 122]
  [waiter.kv.EncryptedKeyValueStore retrieve kv.clj 167]
  [waiter.kv.CachedKeyValueStore$fn__23591 invoke kv.clj 202]
  [waiter.util.utils$atom_cache_get_or_load$fn__16884 invoke utils.clj 90]
  [clojure.lang.Delay deref Delay.java 37]
  [clojure.core$deref invokeStatic core.clj 2228]
  [clojure.core$deref invoke core.clj 2214]
  [waiter.util.utils$atom_cache_get_or_load$fn__16886$fn__16887 invoke utils.clj 91]
  [clojure.core.cache$through$fn__5673 invoke cache.clj 55]
  [clojure.core.cache$default_wrapper_fn invokeStatic cache.clj 42]
  [clojure.core.cache$default_wrapper_fn invoke cache.clj 42]
  [clojure.core.cache$through invokeStatic cache.clj 55]
  [clojure.core.cache$through invoke cache.clj 44]
  [clojure.core.cache$through invokeStatic cache.clj 51]
  [clojure.core.cache$through invoke cache.clj 44]
  [waiter.util.utils$atom_cache_get_or_load$fn__16886 invoke utils.clj 91]
  [clojure.lang.Atom swap Atom.java 37]
  [clojure.core$swap_BANG_ invokeStatic core.clj 2260]
  [clojure.core$swap_BANG_ invoke core.clj 2253]
  [waiter.util.utils$atom_cache_get_or_load invokeStatic utils.clj 91]
  [waiter.util.utils$atom_cache_get_or_load invoke utils.clj 85]
  [waiter.kv.CachedKeyValueStore retrieve kv.clj 202]
  [waiter.kv$fetch invokeStatic kv.clj 54]
  [waiter.kv$fetch doInvoke kv.clj 50]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [waiter.service_description$token__GT_token_data invokeStatic service_description.clj 497]
  [waiter.service_description$token__GT_token_data invoke service_description.clj 494]
  [waiter.service_description$token__GT_service_parameter_template invokeStatic service_description.clj 531]
  [waiter.service_description$token__GT_service_parameter_template doInvoke service_description.clj 528]
  [clojure.lang.RestFn invoke RestFn.java 464]
  [waiter.core$fn__41705$fnk41702_positional__41706$wrap_auth_bypass_fn__41707$fn__41709 invoke core.clj 1355]
  [waiter.core$ring_handler_factory$http_handler__37736 invoke core.clj 138]
  [waiter.cors$wrap_cors_preflight$wrap_cors_preflight_fn__18040 invoke cors.clj 61]
  [waiter.core$wrap_error_handling$wrap_error_handling_fn__37851 invoke core.clj 224]
  [waiter.core$wrap_debug$wrap_debug_fn__37840 invoke core.clj 217]
  [waiter.request_log$wrap_log$fn__43546 invoke request_log.clj 76]
```

### PR DESCRIPTION
**Pull request by nsinkov**
## Changes proposed in this PR

- detects invalid zookeeper key exception and report status 400 instead of 500

## Why are we making these changes?

Fixes #454.

### CODE REVIEW

File: waiter/src/waiter/service_description.clj [hunk 1]
```diff
@@ -496,7 +496,15 @@
 (defn- token->token-data
   "Retrieves the data stored against the token in the kv-store."
   [kv-store ^String token allowed-keys error-on-missing include-deleted]
-  (let [{:strs [deleted run-as-user] :as token-data} (when token (kv/fetch kv-store token))
+  (let [{:strs [deleted run-as-user] :as token-data}
+        (when token (try
```
Comment (shamsimam) [inline waiter/src/waiter/service_description.clj]: Please move the `try` to the new line.

File: waiter/src/waiter/kv.clj [hunk 2]
```diff
@@ -94,9 +95,9 @@
   given the underlying ZooKeeper implementation."
   [key]
   (when (re-matches #".*/.*" key)
-    (throw (ex-info "Key may not contain '/'" {:key key})))
+    (throw (ex-info "Key may not contain '/'" {:key key :ex-type ::invalid-zk-key})))
   (when (re-matches #"^\..*" key)
-    (throw (ex-info "Key may not begin with '.'" {:key key}))))
+    (throw (ex-info "Key may not begin with '.'" {:key key :ex-type ::invalid-zk-key}))))
```
Comment (shamsimam) [inline waiter/src/waiter/kv.clj]: Nitpick: lexicographic ordering in the map.

File: waiter/src/waiter/kv.clj [hunk 3]
```diff
@@ -94,9 +95,9 @@
   given the underlying ZooKeeper implementation."
   [key]
   (when (re-matches #".*/.*" key)
-    (throw (ex-info "Key may not contain '/'" {:key key})))
+    (throw (ex-info "Key may not contain '/'" {:key key :ex-type ::invalid-zk-key})))
```
Comment (shamsimam) [inline waiter/src/waiter/kv.clj]: Nitpick: lexicographic ordering in the map.

Comment (shamsimam) [inline waiter/src/waiter/kv.clj]: Can we change this to `invlaid-key` so that users of this keyword don't have to know the exception was thrown from ZK?

File: waiter/src/waiter/service_description.clj [hunk 4]
```diff
@@ -496,7 +496,15 @@
...
+                      (kv/fetch kv-store token)
+                      (catch Exception e
+                        (let [{:keys [ex-type] :as exception-data} (ex-data e)]
+                          (if (= ex-type ::kv/invalid-zk-key)
```
Comment (shamsimam) [inline waiter/src/waiter/service_description.clj]: I don't like that we need to know this came from ZK, using just `kv/invalid-key` would be better as it could be thrown from any of the KV implementations.

File: waiter/src/waiter/token.clj [hunk 5]
```diff
@@ -330,7 +330,7 @@
     (when (some #(= token %) waiter-hostnames)
       (throw (ex-info "Token name is reserved" {:status 403 :token token})))
     (when-not (re-matches valid-token-re token)
-      (throw (ex-info "Token must match pattern"
+      (throw (ex-info "Token must be two or more characters, contain alphanumeric, '-', '_', '$', or '.' characters and must start with a letter"
```
Comment (shamsimam) [inline waiter/src/waiter/token.clj]: How do you like:
`"Token must be two or more characters, must start with a letter and contain letters, digits, '-', or '.'"`

Comment (shamsimam) [reply waiter/src/waiter/token.clj]: Also, this change is not relevant to this PR.

Comment (shamsimam) [reply waiter/src/waiter/token.clj]: Something for another PR, we need to improve our token regex, currently it is legl to use `a..-_...`.
Created #483.

File: waiter/test/waiter/token_test.clj [hunk 6]
```diff
@@ -1114,7 +1114,7 @@
                  :body (StringBufferInputStream. (utils/clj->json service-description))
                  :request-method :post})]
           (is (= 400 status))
-          (is (str/includes? body "Token must match pattern"))))
+          (is (str/includes? body "Token must be two or more characters"))))
```
Comment (shamsimam) [inline waiter/test/waiter/token_test.clj]: Not relevant to this PR.
